language: java
jdk:
  - oraclejdk8
script:
  - mvn test -B -Pjacoco
after_success:
  - bash <(curl -s https://codecov.io/bash)
after_script:
  - "[ x$TRAVIS_PULL_REQUEST = x ] && mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=fabric8 -Dsonar.login=${SONAR_TOKEN}"
  
