version: 2
jobs:
  doc:
    filters:
      branches:
        only: dmp.fabric8.io
    working_directory: ~/fabric8io/docker-maven-plugin
    docker:
    - image: circleci/node:8-browsers
    steps:
    - checkout
    - run:
      - git config --global user.email "circleci@fabric8.io"
      - git config --global user.name "CircleCI"
    - run: ./doc/ci-docs.sh
